using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CardsAgainstHumanity.Core.Cards
{
    public class MainSet
        : CardSet
    {
        protected override Dictionary<string, int> BlackCards => new Dictionary<string, int>()
        {
            { "Why can't I sleep at night?", 1 },
            { "I got 99 problems but _ ain't one.", 1 },
            { "What's a girl's best friend?", 1 },
            { "What's that smell?", 1 },
            { "This is the way the world ends / This is the way the world ends / Not with a bang but with _.", 1 },
            { "What is Batman's guilty pleasure?", 1 },
            { "TSA guidelines now prohibit _ on airplanes.", 1 },
            { "What ended my last relationship?", 1 },
            { "MTV's new reality show features eight washed-up celebrities living with _.", 1 },
            { "I drink to forget _.", 1 },
            { "I'm sorry, Professor, but I couldn't complete my homework because of _.", 1 },
            { "Alternative medicine is now embracing the curative powers of _.", 1 },
            { "What's that sound?", 1 },
            { "What's the next Happy Meal® toy?", 1 },
            { "It's a pity that kids these days are all getting involved with _.", 1 },
            { "In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.", 1 },
            { "_. That's how I want to die.", 1 },
            { "What does Dick Cheney prefer?", 1 },
            { "What's the most emo?", 1 },
            { "Instead of coal, Santa now gives the bad children _.", 1 },
            { "Next from J.K. Rowling: Harry Potter and the Chamber of _.", 1 },
            { "A romantic, candlelit dinner would be incomplete without _.", 1 },
            { "White people like _.", 1 },
            { "_. Betcha can't have just one!", 1 },
            { "War!What is it good for?", 1 },
            { "BILLY MAYS HERE FOR _.", 1 },
            { "_. High five, bro.", 1 },
            { "During sex, I like to think about _.", 1 },
            { "What did I bring back from Mexico?", 1 },
            { "What are my parents hiding from me?", 1 },
            { "What will always get you laid?", 1 },
            { "What would grandma find disturbing, yet oddly charming?", 1 },
            { "What did the U.S. airdrop to the children of Afghanistan?", 1 },
            { "What helps Obama unwind?", 1 },
            { "What's there a ton of in heaven?", 1 },
            { "Major League Baseball has banned _ for giving players an unfair advantage.", 1 },
            { "When I am a billionaire, I shall erect a 50-foot statue to commemorate _.", 1 },
            { "What's the new fad diet?", 1 },
            { "When I am the President of the United States, I will create the Department of _.", 1 },
            { "_. It's a trap!", 1 },
            { "How am I maintaining my relationship status?", 1 },
            { "What will I bring back in time to convince people that I am a powerful wizard?", 1 },
            { "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.", 1 },
            { "Coming to Broadway this season, _: The Musical.", 1 },
            { "What's my secret power?", 1 },
            { "What gives me uncontrollable gas?", 1 },
            { "But before I kill you, Mr. Bond, I must show you _.", 1 },
            { "What never fails to liven up the party?", 1 },
            { "What am I giving up for Lent?", 1 },
            { "What do old people smell like? ", 1 },
            { "The class field trip was completely ruined by _.", 1 },
            { "When Pharaoh remained unmoved, Moses called down a plague of _.", 1 },
            { "I do not know with which weapons World War III will be fought, but World War IV will be fought with _.", 1 },
            { "What's Teach for America using to inspire inner city students to succeed?", 1 },
            { "In Michael Jackson's final moments, he thought about _.", 1 },
            { "Why do I hurt all over?", 1 },
            { "Studies show that lab rats navigate mazes 50% faster after being exposed to _.", 1 },
            { "Why am I sticky?", 1 },
            { "What's my anti-drug?", 1 },
            { "And the Academy Award for _ goes to _.", 2 },
            { "For my next trick, I will pull _ out of _.", 2 },
            { "_: Good to the last drop.", 1 },
            { "What did Vin Diesel eat for dinner?", 1 },
            { "_: kid-tested, mother-approved.", 1 },
            { "What gets better with age?", 1 },
            { "I never truly understood _ until I encountered _.", 2 },
            { "Rumor has it that Vladimir Putin's favorite delicacy is _ stuffed with _.", 2 },
            { "Lifetime® presents _, the story of _.", 2 },
            { "Make a haiku.", 3 },
            { "In M. Night Shyamalan's new movie, Bruce Willis discovers that _ had really been _ all along.", 2 },
            { "_ is a slippery slope that leads to _.", 2 },
            { "In a world ravaged by _, our only solace is _.", 2 },
            { "That's right, I killed _. How, you ask? _.", 2 },
            { "When I was tripping on acid, _ turned into _.", 2 },
            { "_ + _ = _.", 3 },
            { "What's the next superhero/sidekick duo?", 2 },
            { "Dear Abby,I'm having some trouble with _ and would like your advice.", 1 },
            { "After the earthquake, Sean Penn brought _ to the people of Haiti.", 1 },
            { "In L.A. County Jail, word is you can trade 200 cigarettes for _.", 1 },
            { "Maybe she's born with it. Maybe it's _.", 1 },
            { "Life for American Indians was forever changed when the White Man introduced them to _.", 1 },
            { "Next on ESPN2, the World Series of _.", 1 },
            { "Step 1: _. Step 2: _. Step 3: Profit.", 2 },
            { "Here is the churchHere is the steepleOpen the doorsAnd there is _.", 1 },
            { "How did I lose my virginity?", 1 },
            { "During his childhood, Salvador Dalí produced hundreds of paintings of _.", 1 },
            { "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?", 1 },
            { "What don't you want to find in your Kung Pao chicken?", 1 },
            { "The Smithsonian Museum of Natural History has just opened an exhibit on _.", 1 },
            { "Daddy, why is Mommy crying?", 1 },
            { "What brought the orgy to a grinding halt?", 1 },
            { "When I pooped, what came out of my butt?", 1 },
            { "In the distant future, historians will agree that _ marked the beginning of America's decline.", 1 },
            { "What's the gift that keeps on giving?", 1 },
            { "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only _ and his wits.", 1 },
            { "Michael Bay's new three-hour action epic pits _ against _.", 2 },
            { "And I would have gotten away with it, too, if it hadn't been for _!", 1 },
            { "In a pinch, _ can be a suitable substitute for _.", 2 },
            { "What has been making life difficult at the nudist colony?", 1 },
            { "Science will never explain the origin of _.", 1 },
            { "In Rome, there are whisperings that the Vatican has a secret room devoted to _.", 1 },
            { "I learned the hard way that you can't cheer up a grieving friend with _.", 1 },
            { "When all else fails, I can always masturbate to _.", 1 },
            { "An international tribunal has found _ guilty of _.", 2 },
            { "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated _.", 1 },
            { "In his new self-produced album, Kanye West raps over the sounds of _.", 1 },
            { "The socialist governments of Scandinavia have declared that access to _ is a basic human right.", 1 },
            { "He who controls _ controls the world.", 1 },
            { "Dear Sir or Madam, We regret to inform you that the Office of _ has denied your request for _.", 2 },
            { "The CIA now interrogates enemy agents by repeatedly subjecting them to _.", 1 },
            { "_ would be woefully incomplete without _.", 2 },
            { "During his midlife crisis, my dad got really into _.", 1 },
            { "Before I run for president, I must destroy all evidence of my involvement with _.", 1 },
            { "My new favorite porn star is Joey \"_\" McGee.", 1 },
            { "In his newest and most difficult stunt, David Blaine must escape from _.", 1 },
            { "This is your captain speaking. Fasten your seatbelts and prepare for _.", 1 },
            { "My mom freaked out when she looked at my browser history and found _.com/_.", 2 },
            { "The Five Stages of Grief: denial, anger, bargaining, _, acceptance.", 1 },
            { "Members of New York's social elite are paying thousands of dollars just to experience _.", 1 },
            { "I went from _ to _, all thanks to _.", 3 },
            { "Little Miss Muffet Sat on a tuffet, Eating her curds and _.", 1 },
            { "This month's Cosmo: \"Spice up your sex life by bringing _ into the bedroom.\"", 1 },
            { "If God didn't want us to enjoy _, he wouldn't have given us _.", 2 },
            { "My country, 'tis of thee, sweet land of _.", 1 },
            { "After months of debate, the Occupy Wall Street General Assembly could only agree on \"More _!\"", 1 },
            { "I spent my whole life working toward _, only to have it ruined by _.", 2 },
            { "Next time on Dr. Phil: How to talk to your child about _.", 1 },
            { "Only two things in life are certain: death and _.", 1 },
            { "Everyone down on the ground! We don't want to hurt anyone. We're just here for _.", 1 },
            { "The healing process began when I joined a support group for victims of _.", 1 },
            { "The votes are in, and the new high school mascot is _.", 1 },
            { "Charades was ruined for me forever when my mom had to act out _.", 1 },
            { "Before _, all we had was _.", 2 },
            { "Tonight on 20/20: What you don't know about _ could kill you.", 1 },
            { "You haven't truly lived until you've experienced _ and _ at the same time.", 2 },
            { "Hey baby, come back to my place and I'll show you _.", 1 },
            { "My gym teacher got fired for adding _ to the obstacle course.", 1 },
            { "Finally! A service that delivers _ right to your door.", 1 },
            { "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of _.", 1 },
            { "My life is ruled by a vicious cycle of _ and _.", 2 },
            { "During high school, I never really fit in until I found _ club.", 1 },
            { "Money can't buy me love, but it can buy me _.", 1 },
            { "Listen, son. If you want to get involved with _, I won't stop you. Just steer clear of _.", 2 },
            { "A successful job interview begins with a firm handshake and ends with _.", 1 },
            { "Call the law offices of Goldstein & Goldstein, because no one should have to tolerate _ in the workplace.", 1 },
            { "Lovin' you is easy 'cause you're _.", 1 },
            { "The blind date was going horribly until we discovered our shared interest in _.", 1 },
            { "What left this stain on my couch?", 1 },
            { "Turns out that _-Man was neither the hero we needed nor wanted.", 1 },
            { "After months of practice with _, I think I'm finally ready for _.", 2 },
            { "In the seventh circle of Hell, sinners must endure _ for all eternity.", 1 },
            { "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for _.", 1 },
            { "When you get right down to it, _ is just _.", 2 },
            { "Having problems with _? Try _!", 2 },
            { "And what did you bring for show and tell?", 1 },
            { "I'm not like the rest of you. I'm too rich and busy for _.", 1 },
            { "With enough time and pressure, _ will turn into _.", 2 },
            { "_: Hours of fun. Easy to use. Perfect for _!", 2 },
            { "_. Awesome in theory, kind of a mess in practice.", 1 },
            { "As part of his contract, Prince won't perform without _ in his dressing room.", 1 },
            { "Man, this is bullshit. Fuck _.", 1 },
            { "Dear Leader Kim Jong-un,our village praises your infinite wisdom with a humble offering of _.", 1 },
            { "_ may pass, but _ will last forever.", 2 },
            { "She's up all night for good fun.I'm up all night for _.", 1 },
            { "Alright, bros. Our frat house is condemned, and all the hot slampieces are over at Gamma Phi. The time has come to commence Operation _.", 1 },
            { "The Japanese have developed a smaller, more efficient version of _.", 1 },
            { "In return for my soul, the Devil promised me _, but all I got was _.", 2 },
            { "You guys, I saw this crazy movie last night. It opens on _, and then there's some stuff about _, and then it ends with _.", 3 },
            { "_ will never be the same after _.", 2 },
            { "Wes Anderson's new film tells the story of a precocious child coming to terms with _.", 1 },
            { "In the beginning, there was _.And the Lord said, \"Let there be _.\"", 2 },
            { "What's fun until it gets weird?", 1 },
            { "We never did find _, but along the way we sure learned a lot about _.", 2 },
            { "You've seen the bearded lady!You've seen the ring of fire!Now, ladies and gentlemen, feast your eyes upon _!", 1 },
            { "How am I compensating for my tiny penis?", 1 },
            { "I'm sorry, sir, but we don't allow _ at the country club.", 1 },
            { "2 AM in the city that never sleeps. The door swings open and she walks in, legs up to here. Something in her eyes tells me she's looking for _.", 1 },
            { "As king, how will I keep the peasants in line?", 1 },
            { "Oprah's book of the month is \"_ For _: A Story of Hope.\"", 2 },
            { "Do not fuck with me! I am literally _ right now.", 1 },
            { "Adventure.Romance._.From Paramount Pictures, \"_.\"", 2 },
            { "I am become _, destroyer of _!", 2 },
            { "It lurks in the night. It hungers for flesh. This summer, no one is safe from _.", 1 },
            { "If you can't handle _, you'd better stay away from _.", 2 },
            { "This is the prime of my life. I'm young, hot, and full of _.", 1 },
            { "I'm pretty sure I'm high right now, because I'm absolutely mesmerized by _.", 1 },
            { "This year's hottest album is \"_\" by _.", 2 },
            { "Every step towards _ gets me a little closer to _.", 2 },
            { "Forget everything you know about _, because now we've supercharged it with _!", 2 },
            { "Honey, I have a new role-play I want to try tonight! You can be _, and I'll be _.", 2 },
            { "Do the Dew ® with our most extreme flavor yet! Get ready for Mountain Dew _!", 1 },
            { "Armani suit: $1,000. Dinner for two at that swanky restaurant: $300. The look on her face when you surprise her with _: priceless.", 1 },
            { "In his new action comedy, Jackie Chan must fend off ninjas while also dealing with _.", 1 },
            { "Well what do you have to say for yourself, Casey? This is the third time you've been sent to the principal's office for _.", 1 },
            { "Here at the Academy for Gifted Children, we allow students to explore _ at their own pace.", 1 },
            { "Heed my voice, mortals! I am the god of _, and I will not tolerate _!", 2 },
            { "I don't mean to brag, but they call me the Michael Jordan of _.", 1 },
            { "Why am I broke?", 1 },
            { "Help me doctor, I've got _ in my butt!", 1 },
            { "Hi MTV! My name is Kendra, I live in Malibu, I'm into _, and I love to have a good time.", 1 },
            { "Patient presents with _. Likely a result of _.", 2 },
            { "Life's pretty tough in the fast lane. That's why I never leave the house without _.", 1 },
            { "What's making things awkward in the sauna?", 1 },
            { "Get ready for the movie of the summer! One cop plays by the book. The other's only interested in one thing: _.", 1 },
            { "Having the worst day EVER. #_", 1 },
            { "In his farewell address, George Washington famously warned Americans about the dangers of _.", 1 },
            { "Don't forget! Beginning this week, Casual Friday will officially become \"_ Friday.\"", 1 },
            { "What killed my boner?", 1 },
            { "Yo' mama so fat she _!", 1 },
            { "Well if _ is good enough for _, it's good enough for me.", 2 },
            { "Hi, this is Jim from accounting. We noticed a $1,200 charge labeled \"_\". Can you explain?", 1 },
            { "Do you lack energy? Does it sometimes feel like the whole world is _? Zoloft.®", 1 },
            { "WHOOO! God damn I love _!", 1 },
            { "Now in bookstores: \"The Audacity of _\", by Barack Obama.", 1 },
            { "And today's soup is Cream of _.", 1 },
            { "I work my ass off all day for this family, and this is what I come home to? _!?", 1 },
            { "I have a strict policy. First date, dinner. Second date, kiss. Third date, _.", 1 },
            { "When I was a kid, we used to play Cowboys and _.", 1 },
            { "This is America. If you don't work hard, you don't succeed. I don't care if you're black, white, purple, or _.", 1 },
            { "You Won't Believe These 15 Hilarious _ Bloopers!", 1 },
            { "James is a lonely boy. But when he discovers a secret door in his attic, he meets a magical new friend: _.", 1 },
            { "Don't worry kid. It gets better. I've been living with _ for 20 years.", 1 },
            { "My grandfather worked his way up from nothing. When he came to this country, all he had was the shoes on his feet and _.", 1 },
            { "Behind every powerful man is _.", 1 },
            { "You are not alone. Millions of Americans struggle with _ every day.", 1 },
            { "Come to Dubai, where you can relax in our world famous spas, experience the nightlife, or simply enjoy _ by the poolside.", 1 },
            { "\"This is madness.\" \"No, THIS IS _!\"", 1 },
            { "Listen Gary, I like you. But if you want that corner office, you're going to have to show me _.", 1 },
            { "I went to the desert and ate of the peyote cactus. Turns out my spirit animal is _.", 1 },
            { "And would you like those buffalo wings mild, hot, or _?", 1 },
            { "The six things I could never do without: oxygen, Facebook, chocolate, Netflix, friends, and _ LOL!", 1 },
            { "Why won't you make love to me anymore? Is it _?", 1 },
            { "Puberty is a time of change. You might notice hair growing in new places. You might develop an interest in _. This is normal.", 1 },
            { "I'm sorry, Mrs. Chen, but there was nothing we could do. At 4:15 this morning, your son succumbed to _.", 1 },
            { "I'm Miss Tennessee, and if I could make the world better by changing one thing, I would get rid of _.", 1 },
            { "Tonight we will have sex. And afterwards, If you'd like, a little bit of _.", 1 },
            { "Everybody join hands and close your eyes. Do you sense that? That's the presence of _ in this room.", 1 },
            { "To become a true Yanomamo warrior, you must prove that you can withstand _ without crying out.", 1 },
            { "Y'all ready to get this thing started? I'm Nick Cannon, and this is America's Got _.", 1 },
            { "If you had to describe the Card Czar, using only one of the cards in your hand, which one would it be?", 1 },
            { "Siskel and Ebert have panned _ as \"poorly conceived\" and \"sloppily executed.\"", 1 },
            { "Up next on Nickelodeon: \"Clarissa Explains _.\"", 1 },
            { "Believe it or not, Jim Carrey can do a dead-on impression of _.", 1 },
            { "It's Morphin' Time! Mastadon! Pterodactyl! Triceratops! Sabertooth Tiger! _!", 1 },
            { "I'm a bitch, I'm a lover, I'm a child, I'm _.", 1 },
            { "How did Stella get her groove back?", 1 },
            { "Tonight on SNICK: \"Are You Afraid of _?\"", 1 },
            { "And in the end, the dragon was not evil; he just wanted _.", 1 },
            { "Critics are raving about HBO's new Game of Thrones spin-off, \"_ of _.\"", 2 },
            { "Having tired of poetry and music, the immortal elves now fill their days with _.", 1 },
            { "Legend tells of a princess who has been asleep for a thousand years and can only be awoken by _.", 1 },
            { "Who blasphemes and bubbles at the center of all infinity, whose name no lips dare speak aloud, and who gnaws hungrily in inconceivable, unlighted chambers beyond time?", 1 },
            { "Your father was a powerful wizard, Harry. Before he died, he left you something very precious: _.", 1 },
            { "I'm Bobby Flay, and if you can't stand _, get out of the kitchen!", 1 },
            { "It's not delivery. It's _.", 1 },
            { "Aw babe, your burps smell like _!", 1 },
            { "Don't miss Rachel Ray's hit new show, Cooking with _.", 1 },
            { "Excuse me, waiter. Could take this back? This soup tastes like _.", 1 },
            { "Now on Netflix: Jiro Dreams of _.", 1 },
            { "In line with our predictions, we find a robust correlation between _ and _ (p>.05).", 2 },
            { "In what's being hailed as a major breakthrough, scientists have synthesized _ in the lab.", 1 },
            { "A study published in Nature this week found that _ is good for you in small doses.", 1 },
            { "In an attempt to recreate conditions just after the Big Bang, physicists at the LHC are observing collisions between _ and _.", 2 },
            { "What really killed the dinosaurs?", 1 },
            { "Hey there, Young Scientists! Put on your labcoats and strap on your safety goggles, because today we're learning about _!", 1 },
            { "Today on MythBusters, we found out how long _ can withstand _.", 2 },
            { "Don't worry, Penny! Go Go Gadget _!", 1 },
            { "I need you like _ needs _.", 2 },
            { "I'm just gonna stay in tonight. You know, Netflix and _.", 1 },
            { "Nothing says \"I love you\" like _.", 1 },
            { "Such _. Very _. Wow.", 2 },
            { "This app is basically Tinder, but for _.", 1 },
            { "TRIGGER WARNING: _.", 1 },
            { "What did I nickname my genitals?", 1 },
            { "You guys, you can buy _ on the dark web.", 1 },
            { "When you go to the polls on Tuesday, remember:  a vote for me is a vote for _.", 1 },
            { "As reparations for slavery, all African Americans will receive _.", 1 },
            { "Senator, I trust you enjoyed _ last night.  Now, can I count on your vote?", 1 },
            { "Trump's great!  Trump's got _.  I love that.", 1 },
            { "According to Arizona's stand-your-ground law, you're allowed to shoot someone if they're _.", 1 },
            { "It's 3AM.  The red phone rings.  It's _.  Who do you want answering?", 1 },
            { "After blacking out during New Year's Eve, I was awoken by _.", 1 },
            { "This holiday season, Tim Allen must overcome his fear of _ to save Christmas.", 1 },
            { "Jesus is _.", 1 },
            { "Every Christmas, my uncle gets drunk and tells the story about _.", 1 },
            { "What keeps me warm during the cold, cold winter?", 1 },
            { "On the third day of Christmas, my true love gave to me: three French hens, two turtle doves, and _.", 1 },
            { "Wake up, America. Christmas is under attack by secular liberals and their _.", 1 },
            { "Here's what you can expect for the new year.Out: _.In: _.", 2 },
            { "Revealed:Why He Really Resigned!Pope Benedict's Secret Struggle with _!", 1 },
            { "GREETINGS HUMANSI AM _ BOTEXECUTING PROGRAM", 1 },
            { "Kids these days with their iPods and their Internet. In my day, all we needed to pass the time was _.", 1 },
            { "Because they are forbidden from masturbating, Mormons channel their repressed sexual energy into _.", 1 },
            { "Blessed are you, Lord our God, creator of the universe, who has granted us _.", 1 },
            { "But wait, there's more! If you order _ in the next 15 minutes, we'll throw in _ absolutely free!", 2 },
            { "What's the one thing that makes an elf instantly ejaculate?", 1 },
            { "I really hope my grandmother doesn't ask me to explain _ again.", 1 },
            { "A wise man said, \"Everything is about sex. Except sex. Sex is about _.\"", 1 },
            { "Our relationship is strictly professional. Let's not complicate things with _.", 1 },
            { "Corruption. Betrayal. _. Coming soon to Netflix, \"House of _.\"", 2 },
            { "Because you enjoyed _, we thought you'd like _.", 2 },
            { "I can't believe Netflix is using _ to promote House of Cards.", 1 },
            { "We're not like other news organizations. Here at Slugline, we welcome _ in the office. ", 1 },
            { "I'm not going to lie. I despise _. There, I said it.", 1 },
            { "Cancel all my meetings. We've got a situation with _ that requires my immediate attention.", 1 },
        };

        protected override List<string> WhiteCards => new List<string>()
        {
            "Coat hanger abortions.",
            "Man meat.",
            "Autocannibalism.",
            "Vigorous jazz hands.",
            "Flightless birds.",
            "Pictures of boobs.",
            "Doing the right thing.",
            "The violation of our most basic human rights.",
            "Viagra®.",
            "Self-loathing.",
            "Spectacular abs.",
            "A balanced breakfast.",
            "Roofies.",
            "Concealing a boner.",
            "Amputees.",
            "The Big Bang.",
            "Former President George W. Bush.",
            "The Rev. Dr. Martin Luther King, Jr.",
            "Smegma.",
            "Being marginalized.",
            "Cuddling.",
            "Laying an egg.",
            "The Pope.",
            "Aaron Burr.",
            "Genital piercings.",
            "Fingering.",
            "A bleached asshole.",
            "Horse meat.",
            "Fear itself.",
            "Science.",
            "Elderly Japanese men.",
            "Stranger danger.",
            "The terrorists.",
            "Praying the gay away.",
            "Same-sex ice dancing.",
            "Ethnic cleansing.",
            "Cheating in the Special Olympics.",
            "German dungeon porn.",
            "Bingeing and purging.",
            "Making a pouty face.",
            "William Shatner.",
            "Heteronormativity.",
            "Nickelback.",
            "Tom Cruise.",
            "The profoundly handicapped.",
            "The placenta.",
            "Chainsaws for hands.",
            "Arnold Schwarzenegger.",
            "An icepick lobotomy.",
            "Goblins.",
            "Object permanence.",
            "Dying.",
            "Foreskin.",
            "A falcon with a cap on its head.",
            "Hormone injections.",
            "Dying of dysentery.",
            "Sexy pillow fights.",
            "The invisible hand.",
            "A really cool hat.",
            "Sean Penn.",
            "Heartwarming orphans.",
            "The clitoris.",
            "The Three-Fifths compromise.",
            "A sad handjob.",
            "Men.",
            "Historically black colleges.",
            "A micropenis.",
            "Raptor attacks.",
            "Agriculture.",
            "Vikings.",
            "Pretending to care.",
            "The Underground Railroad.",
            "My humps.",
            "Being a dick to children.",
            "Geese.",
            "Bling.",
            "Sniffing glue.",
            "The South.",
            "An Oedipus complex.",
            "Eating all of the cookies before the AIDS bake-sale.",
            "Sexting.",
            "YOU MUST CONSTRUCT ADDITIONAL PYLONS.",
            "Mutually-assured destruction.",
            "Sunshine and rainbows.",
            "Count Chocula.",
            "Sharing needles.",
            "Being rich.",
            "Skeletor.",
            "A sausage festival.",
            "Michael Jackson.",
            "Emotions.",
            "Farting and walking away.",
            "The Chinese gymnastics team.",
            "Necrophilia.",
            "Spontaneous human combustion.",
            "Yeast.",
            "Leaving an awkward voicemail.",
            "Dick Cheney.",
            "White people.",
            "Penis envy.",
            "Teaching a robot to love.",
            "Sperm whales.",
            "Scrubbing under the folds.",
            "Panda sex.",
            "Whipping it out.",
            "Catapults.",
            "Masturbation.",
            "Natural selection.",
            "Opposable thumbs.",
            "A sassy black woman.",
            "AIDS.",
            "The KKK.",
            "Figgy pudding.",
            "Seppuku.",
            "Gandhi.",
            "Preteens.",
            "Toni Morrison's vagina.",
            "Five-Dollar Footlongs™;.",
            "Land mines.",
            "A sea of troubles.",
            "A zesty breakfast burrito.",
            "Christopher Walken.",
            "Friction.",
            "Balls.",
            "Dental dams.",
            "A can of whoop-ass.",
            "A tiny horse.",
            "Waiting 'til marriage.",
            "Authentic Mexican cuisine.",
            "Genghis Khan.",
            "Old-people smell.",
            "Feeding Rosie O'Donnell.",
            "Pixelated bukkake.",
            "Friends with benefits.",
            "The token minority.",
            "The Tempur-Pedic® Swedish Sleep System™;.",
            "A thermonuclear detonation.",
            "Take-backsies.",
            "The Rapture.",
            "A cooler full of organs.",
            "Sweet, sweet vengeance.",
            "RoboCop.",
            "Keanu Reeves.",
            "Drinking alone.",
            "Giving 110%.",
            "Flesh-eating bacteria.",
            "The American Dream.",
            "Taking off your shirt.",
            "Me time.",
            "A murder most foul.",
            "The inevitable heat death of the universe.",
            "The folly of man.",
            "That thing that electrocutes your abs.",
            "Cards Against Humanity.",
            "Fiery poops.",
            "Poor people.",
            "Edible underpants.",
            "Britney Spears at 55.",
            "All-you-can-eat shrimp for $4.99.",
            "Pooping back and forth. Forever.",
            "Fancy Feast®.",
            "Jewish fraternities.",
            "Being a motherfucking sorcerer.",
            "Pulling out.",
            "Picking up girls at the abortion clinic.",
            "The homosexual agenda.",
            "The Holy Bible.",
            "Passive-agression.",
            "Ronald Reagan.",
            "Vehicular manslaughter.",
            "Nipple blades.",
            "Assless chaps.",
            "Full frontal nudity.",
            "Hulk Hogan.",
            "Daddy issues.",
            "The hardworking Mexican.",
            "Natalie Portman.",
            "Waking up half-naked in a Denny's parking lot.",
            "God.",
            "Sean Connery.",
            "Saxophone solos.",
            "Gloryholes.",
            "The World of Warcraft.",
            "Homeless people.",
            "Scalping.",
            "Darth Vader.",
            "Eating the last known bison.",
            "Guys who don't call.",
            "Hot Pockets®.",
            "A time travel paradox.",
            "The milk man.",
            "Testicular torsion.",
            "Dropping a chandelier on your enemies and riding the rope up.",
            "World peace.",
            "A salty surprise.",
            "Poorly-timed Holocaust jokes.",
            "Smallpox blankets.",
            "Licking things to claim them as your own.",
            "The heart of a child.",
            "Robert Downey, Jr.",
            "Lockjaw.",
            "Eugenics.",
            "A good sniff.",
            "Friendly fire.",
            "The taint; the grundle; the fleshy fun-bridge.",
            "Wearing underwear inside-out to avoid doing laundry.",
            "Hurricane Katrina.",
            "Free samples.",
            "Jerking off into a pool of children's tears.",
            "A foul mouth.",
            "The glass ceiling.",
            "Republicans.",
            "Explosions.",
            "Michelle Obama's arms.",
            "Getting really high.",
            "Attitude.",
            "Sarah Palin.",
            "The Übermensch.",
            "Altar boys.",
            "My soul.",
            "My sex life.",
            "Pedophiles.",
            "72 virgins.",
            "Pabst Blue Ribbon.",
            "Domino's™; Oreo™; Dessert Pizza.",
            "A snapping turtle biting the tip of your penis.",
            "The Blood of Christ.",
            "Half-assed foreplay.",
            "My collection of high-tech sex toys.",
            "A middle-aged man on roller skates.",
            "Bitches.",
            "Bill Nye the Science Guy.",
            "Italians.",
            "A windmill full of corpses.",
            "Adderall™;.",
            "Crippling debt.",
            "A stray pube.",
            "Prancing.",
            "Passing a kidney stone.",
            "A brain tumor.",
            "Leprosy.",
            "Puppies!",
            "Bees?",
            "Frolicking.",
            "Repression.",
            "Road head.",
            "A bag of magic beans.",
            "An asymmetric boob job.",
            "Dead parents.",
            "Public ridicule.",
            "A mating display.",
            "A mime having a stroke.",
            "Stephen Hawking talking dirty.",
            "African children.",
            "Mouth herpes.",
            "Overcompensation.",
            "Riding off into the sunset.",
            "Being on fire.",
            "Tangled Slinkys.",
            "Civilian casualties.",
            "Auschwitz.",
            "My genitals.",
            "Not reciprocating oral sex.",
            "Lactation.",
            "Being fabulous.",
            "Shaquille O'Neal's acting career.",
            "My relationship status.",
            "Asians who aren't good at math.",
            "Alcoholism.",
            "Incest.",
            "Grave robbing.",
            "Hope.",
            "8 oz. of sweet Mexican black-tar heroin.",
            "Kids with ass cancer.",
            "Winking at old people.",
            "The Jews.",
            "Justin Bieber.",
            "Doin' it in the butt.",
            "A lifetime of sadness.",
            "The Hamburglar.",
            "Swooping.",
            "Classist undertones.",
            "New Age music.",
            "Not giving a shit about the Third World.",
            "The Kool-Aid Man.",
            "A hot mess.",
            "Tentacle porn.",
            "Lumberjack fantasies.",
            "The gays.",
            "Scientology.",
            "Estrogen.",
            "GoGurt®.",
            "Judge Judy.",
            "Dick fingers.",
            "Racism.",
            "Surprise sex!",
            "Police brutality.",
            "Passable transvestites.",
            "The Virginia Tech Massacre.",
            "When you fart and a little bit comes out.",
            "Oompa-Loompas.",
            "A fetus.",
            "Obesity.",
            "Tasteful sideboob.",
            "Hot people.",
            "BATMAN!!!",
            "Black people.",
            "A gassy antelope.",
            "Sexual tension.",
            "Third base.",
            "Racially-biased SAT questions.",
            "Porn stars.",
            "A Super Soaker™; full of cat pee.",
            "Muhammed (Praise Be Unto Him).",
            "Puberty.",
            "A disappointing birthday party.",
            "An erection that lasts longer than four hours.",
            "White privilege.",
            "Getting so angry that you pop a boner.",
            "Wifely duties.",
            "Two midgets shitting into a bucket.",
            "Queefing.",
            "Wiping her butt.",
            "Golden showers.",
            "Barack Obama.",
            "Nazis.",
            "A robust mongoloid.",
            "An M. Night Shyamalan plot twist.",
            "Getting drunk on mouthwash.",
            "Lunchables™;.",
            "Women in yogurt commercials.",
            "John Wilkes Booth.",
            "Powerful thighs.",
            "Mr. Clean, right behind you.",
            "Multiple stab wounds.",
            "Cybernetic enhancements.",
            "Serfdom.",
            "Kanye West.",
            "Women's suffrage.",
            "Children on leashes.",
            "Harry Potter erotica.",
            "The Dance of the Sugar Plum Fairy.",
            "Lance Armstrong's missing testicle.",
            "Parting the Red Sea.",
            "The Amish.",
            "Dead babies.",
            "Child beauty pageants.",
            "AXE Body Spray.",
            "Centaurs.",
            "Copping a feel.",
            "Grandma.",
            "Famine.",
            "The Trail of Tears.",
            "The miracle of childbirth.",
            "Finger painting.",
            "A monkey smoking a cigar.",
            "The Make-A-Wish® Foundation.",
            "Anal beads.",
            "The Force.",
            "Kamikaze pilots.",
            "Dry heaving.",
            "Active listening.",
            "Ghosts.",
            "The Hustle.",
            "Peeing a little bit.",
            "Another goddamn vampire movie.",
            "Shapeshifters.",
            "The Care Bear Stare.",
            "Hot cheese.",
            "A mopey zoo lion.",
            "A defective condom.",
            "Teenage pregnancy.",
            "A Bop It™;.",
            "Expecting a burp and vomiting on the floor.",
            "Horrifying laser hair removal accidents.",
            "Boogers.",
            "Unfathomable stupidity.",
            "Breaking out into song and dance.",
            "Soup that is too hot.",
            "Morgan Freeman's voice.",
            "Getting naked and watching Nickelodeon.",
            "MechaHitler.",
            "Flying sex snakes.",
            "The true meaning of Christmas.",
            "My inner demons.",
            "Pac-Man uncontrollably guzzling cum.",
            "My vagina.",
            "A homoerotic volleyball montage.",
            "Actually taking candy from a baby.",
            "Crystal meth.",
            "Exactly what you'd expect.",
            "Natural male enhancement.",
            "Passive-aggressive Post-it notes.",
            "Inappropriate yodeling.",
            "Lady Gaga.",
            "The Little Engine That Could.",
            "Vigilante justice.",
            "A death ray.",
            "Poor life choices.",
            "A gentle caress of the inner thigh.",
            "Embryonic stem cells.",
            "Nicolas Cage.",
            "Firing a rifle into the air while balls deep in a squealing hog.",
            "Switching to Geico®.",
            "The chronic.",
            "Erectile dysfunction.",
            "Home video of Oprah sobbing into a Lean Cuisine®.",
            "A bucket of fish heads.",
            "50,000 volts straight to the nipples.",
            "Being fat and stupid.",
            "Hospice care.",
            "A pyramid of severed heads.",
            "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.",
            "A subscription to Men's Fitness.",
            "Crucifixion.",
            "A micropig wearing a tiny raincoat and booties.",
            "Some god-damn peace and quiet.",
            "Used panties.",
            "A tribe of warrior women.",
            "The penny whistle solo from \"My Heart Will Go On.\"",
            "An oversized lollipop.",
            "Helplessly giggling at the mention of Hutus and Tutsis.",
            "Not wearing pants.",
            "Consensual sex.",
            "Her Majesty, Queen Elizabeth II.",
            "Funky fresh rhymes.",
            "The art of seduction.",
            "The Devil himself.",
            "Advice from a wise, old black man.",
            "Destroying the evidence.",
            "The light of a billion suns.",
            "Wet dreams.",
            "Synergistic management solutions.",
            "Growing a pair.",
            "Silence.",
            "An M16 assault rifle.",
            "Poopy diapers.",
            "A live studio audience.",
            "The Great Depression.",
            "A spastic nerd.",
            "Rush Limbaugh's soft, shitty body.",
            "Tickling Sean Hannity, even after he tells you to stop.",
            "Stalin.",
            "Brown people.",
            "Rehab.",
            "Capturing Newt Gingrich and forcing him to dance in a monkey suit.",
            "Battlefield amputations.",
            "An uppercut.",
            "Shiny objects.",
            "An ugly face.",
            "Menstrual rage.",
            "A bitch slap.",
            "One trillion dollars.",
            "Chunks of dead prostitute.",
            "The entire Mormon Tabernacle Choir.",
            "The female orgasm.",
            "Extremely tight pants.",
            "The Boy Scouts of America.",
            "Stormtroopers.",
            "Throwing a virgin into a volcano.",
            "Getting in her pants, politely.",
            "Gladiatorial combat.",
            "Good grammar.",
            "Hipsters.",
            "Gandalf.",
            "Genetically engineered super-soldiers.",
            "George Clooney's musk.",
            "Getting abducted by Peter Pan.",
            "Eating an albino.",
            "Enormous Scandinavian women.",
            "Fabricating statistics.",
            "Finding a skeleton.",
            "Suicidal thoughts.",
            "Dancing with a broom.",
            "Deflowering the princess.",
            "Dorito breath.",
            "One thousand Slim Jims.",
            "My machete.",
            "Overpowering your father.",
            "Ominous background music.",
            "Media coverage.",
            "Making the penises kiss.",
            "Moral ambiguity.",
            "Medieval Times® Dinner & Tournament.",
            "Mad hacky-sack skills.",
            "Just the tip.",
            "Literally eating shit.",
            "Leveling up.",
            "Insatiable bloodlust.",
            "Historical revisionism.",
            "Jean-Claude Van Damme.",
            "Jafar.",
            "The boners of the elderly.",
            "The economy.",
            "Statistically validated stereotypes.",
            "Sudden Poop Explosion Disease.",
            "Slow motion.",
            "Space muffins.",
            "Sexual humiliation.",
            "Sexy Siamese twins.",
            "Santa Claus.",
            "Scrotum tickling.",
            "Ripping into a man's chest and pulling out his still-beating heart.",
            "Ryan Gosling riding in on a white horse.",
            "Quivering jowls.",
            "Revenge fucking.",
            "Pistol-whipping a hostage.",
            "Quiche.",
            "Zeus's sexual appetites.",
            "Words, words, words.",
            "Tripping balls.",
            "Being a busy adult with many important things to do.",
            "The four arms of Vishnu.",
            "The shambling corpse of Larry King.",
            "The hiccups.",
            "The harsh light of day.",
            "The Gulags.",
            "The Fanta® girls.",
            "A big black dick.",
            "A beached whale.",
            "A low standard of living.",
            "A nuanced critique.",
            "A bloody pacifier.",
            "A crappy little hand.",
            "Shaft.",
            "Being a dinosaur.",
            "Beating your wives.",
            "Neil Patrick Harris.",
            "Coughing into a vagina.",
            "Carnies.",
            "Nubile slave boys.",
            "Bosnian chicken farmers.",
            "A web of lies.",
            "A rival dojo.",
            "A passionate Latino lover.",
            "Panty raids.",
            "Appreciative snapping.",
            "Apologizing.",
            "Clams.",
            "A woman scorned.",
            "Being awesome at sex.",
            "Spring break!",
            "Another shot of morphine.",
            "Dining with cardboard cutouts of the cast of \"Friends.\"",
            "A soulful rendition of \"Ol' Man River.\"",
            "Making a friend.",
            "A sweaty, panting leather daddy.",
            "Intimacy problems.",
            "The new Radiohead album.",
            "Pretty Pretty Princess Dress-Up Board Game®.",
            "A man in yoga pants with a ponytail and feather earrings.",
            "An army of skeletons.",
            "A squadron of moles wearing aviator goggles.",
            "Beefin' over turf.",
            "The Google.",
            "Bullshit.",
            "A sweet spaceship.",
            "A 55-gallon drum of lube.",
            "Special musical guest, Cher.",
            "The human body.",
            "Mild autism.",
            "Nunchuck moves.",
            "Whipping a disobedient slave.",
            "An ether-soaked rag.",
            "Oncoming traffic.",
            "A dollop of sour cream.",
            "A slightly shittier parallel universe.",
            "My first kill.",
            "Boris the Soviet Love Hammer.",
            "The grey nutrient broth that sustains Mitt Romney.",
            "Tiny nipples.",
            "Power.",
            "Death by Steven Seagal.",
            "A Burmese tiger pit.",
            "Basic human decency.",
            "Grandpa's ashes.",
            "One Ring to rule them all.",
            "The day the birds attacked.",
            "Fetal alcohol syndrome.",
            "Graphic violence, adult language, and some sexual content.",
            "A bigger, blacker dick.",
            "The mere concept of Applebee's®.",
            "A sad fat dragon with no friends.",
            "A piñata full of scorpions.",
            "Existing.",
            "Hillary Clinton's death stare.",
            "Catastrophic urethral trauma.",
            "Double penetration.",
            "Daddy's belt.",
            "Swiftly achieving orgasm.",
            "Mooing.",
            "Rising from the grave.",
            "Subduing a grizzly bear and making her your wife.",
            "Some really fucked-up shit.",
            "Weapons-grade plutonium.",
            "All of this blood.",
            "Scrotal frostbite.",
            "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.",
            "The mixing of the races.",
            "Pumping out a baby every nine months.",
            "Tongue.",
            "Loki, the trickster god.",
            "Whining like a little bitch.",
            "Wearing an octopus for a hat.",
            "An unhinged ferris wheel rolling toward the sea.",
            "Finding Waldo.",
            "Upgrading homeless people to mobile hotspots.",
            "A magic hippie love cloud.",
            "Fuck Mountain.",
            "Living in a trashcan.",
            "The corporations.",
            "Getting hilariously gang-banged by the Blue Man Group.",
            "Jeff Goldblum.",
            "Survivor's guilt.",
            "Me.",
            "All my friends dying.",
            "Shutting the fuck up.",
            "An ass disaster.",
            "Some kind of bird-man.",
            "The entire Internet.",
            "Going around punching people.",
            "A boo-boo.",
            "Indescribable loneliness.",
            "Having sex on top of a pizza.",
            "Chugging a lava lamp.",
            "Warm, velvety muppet sex.",
            "Running naked through a mall, pissing and shitting everywhere.",
            "Nothing.",
            "Samuel L. Jackson.",
            "Self-flagellation.",
            "The systematic destruction of an entire people and their way of life.",
            "The Quesadilla Explosion Salad™; from Chili's®.",
            "Reverse cowgirl.",
            "Vietnam flashbacks.",
            "Actually getting shot, for real.",
            "Not having sex.",
            "Cock.",
            "Dying alone and in pain.",
            "A cop who is also a dog.",
            "The way white people is.",
            "Gay aliens.",
            "The primal, ball-slapping sex your parents are having right now.",
            "A cat video so cute that your eyes roll back and your spine slides out of your anus.",
            "A lamprey swimming up the toilet and latching onto your taint.",
            "Slapping a racist old lady.",
            "A black male in his early 20s, last seen wearing a hoodie.",
            "Jumping out at people.",
            "Three months in the hole.",
            "Blood farts.",
            "The Land of Chocolate.",
            "A botched circumcision.",
            "My manservant, Claude.",
            "Vomiting mid-blowjob.",
            "Letting everyone down.",
            "Having shotguns for legs.",
            "Bill Clinton, naked on a bearskin rug with a saxophone.",
            "Mufasa's death scene.",
            "The Harlem Globetrotters.",
            "Demonic possession.",
            "Fisting.",
            "The thin veneer of situational causality that underlies porn.",
            "Girls that always be textin'.",
            "Blowing some dudes in an alley.",
            "A spontaneous conga line.",
            "A vagina that leads to another dimension.",
            "Disco fever.",
            "Getting your dick stuck in a Chinese finger trap with another dick.",
            "Drinking ten 5-hour ENERGYs® to get fifty continuous hours of energy.",
            "Sneezing, farting, and coming at the same time.",
            "Some douche with an acoustic guitar.",
            "Spending lots of money.",
            "Putting an entire peanut butter and jelly sandwich into the VCR.",
            "An unstoppable wave of fire ants.",
            "A greased-up Matthew McConaughey.",
            "Flying robots that kill people.",
            "Unlimited soup, salad, and breadsticks.",
            "Crying into the pages of Sylvia Plath.",
            "The moist, demanding chasm of his mouth.",
            "Filling every orifice with butterscotch pudding.",
            "An all-midget production of Shakespeare's Richard III.",
            "Screaming like a maniac.",
            "Not contributing to society in any meaningful way.",
            "A pile of squirming bodies.",
            "Buying the right pants to be cool.",
            "Roland the Farter, flatulist to the king.",
            "That ass.",
            "A surprising amount of hair.",
            "Eating Tom Selleck's mustache to gain his powers.",
            "Velcro™;.",
            "A PowerPoint presentation.",
            "Crazy opium eyes.",
            "10 Incredible Facts About the Anus.",
            "An interracial handshake.",
            "Moderate-to-severe joint pain.",
            "Finally finishing off the Indians.",
            "Sugar madness.",
            "Actual mutants with medical conditions and no superpowers.",
            "The secret formula for ultimate female satisfaction.",
            "The complex geopolitical quagmire that is the Middle East.",
            "Fucking a corpse back to life.",
            "Neil Diamond's Greatest Hits.",
            "Calculating every mannerism so as not to suggest homosexuality.",
            "Whatever a McRib® is made of.",
            "No clothes on, penis in vagina.",
            "All the single ladies.",
            "Whispering all sexy.",
            "How awesome I am.",
            "Ass to mouth.",
            "Smoking crack, for instance.",
            "Falling into the toilet.",
            "A dance move that's just sex.",
            "The size of my penis.",
            "Some sort of Asian.",
            "A hopeless amount of spiders.",
            "Party Mexicans.",
            "Drinking responsibly.",
            "The safe word.",
            "Angelheaded hipsters burning for the ancient heavenly connection to the starry dynamo in the machinery of night.",
            "Bouncing up and down.",
            "Jizz.",
            "Ambiguous sarcasm.",
            "A shiny rock that proves I love you.",
            "Dem titties.",
            "My worthless son.",
            "Exploding pigeons.",
            "A Ugandan warlord.",
            "My sex dungeon.",
            "A kiss on the lips.",
            "Child Protective Services.",
            "A Native American who solves crimes by going into the spirit world.",
            "Doo-doo.",
            "The peaceful and nonthreatening rise of China.",
            "Sports.",
            "A fart.",
            "Unquestioning obedience.",
            "Three consecutive seconds of happiness.",
            "Grammar nazis who are also regular Nazis.",
            "Snorting coke off a clown's boner.",
            "Africa.",
            "Depression.",
            "A horse with no legs.",
            "The euphoric rush of strangling a drifter.",
            "Khakis.",
            "Interspecies marriage.",
            "A gender identity that can only be conveyed through slam poetry.",
            "Almost giving money to a homeless person.",
            "Stuff a child's face with Fun Dip® until he starts having fun.",
            "What Jesus would do.",
            "A for-real lizard that spits blood from its eyes.",
            "Blackula.",
            "The tiniest shred of evidence that God is real.",
            "My dad's dumb fucking face.",
            "Prince Ali,fabulous he,Ali Ababwa.",
            "A manhole.",
            "A sex goblin with a carnival penis.",
            "A bunch of idiots playing a card game instead of interacting like normal humans.",
            "A sex comet from Neptune that plunges the Earth into eternal sexiness.",
            "Sharks with legs.",
            "Injecting speed into one arm and horse tranquilizer into the other.",
            "Lots and lots of abortions.",
            "Seeing things from Hitler's perspective",
            "Too much cocaine.",
            "Doing the right stuff to her nipples.",
            "Giant sperm from outer space.",
            "Oil!",
            "Ennui.",
            "A powered exoskeleton.",
            "A disappointing salad.",
            "Mom's new boyfriend.",
            "Unrelenting genital punishment.",
            "Denzel.",
            "The swim team, all at once.",
            "The eight gay warlocks who dictate the rules of fashion.",
            "Being nine years old.",
            "The unbelievable world of mushrooms.",
            "The Abercrombie & Fitch lifestyle.",
            "Vegetarian options.",
            "My first period.",
            "Having been dead for a while.",
            "Backwards knees.",
            "Being paralyzed from the neck down.",
            "Seeing my village burned and my family slaughtered before my eyes.",
            "A zero-risk way to make $2,000 from home.",
            "A crazy little thing called love.",
            "Ancient Athenian boy-fucking",
            "Out-of-this-world bazongas.",
            "The ghost of Marlon Brando.",
            "The basic suffering that pervades all of existence.",
            "Being worshipped as the one true God.",
            "Figuring out how to have sex with a dolphin.",
            "All these decorative pillows.",
            "A mouthful of potato salad.",
            "Russian super-tuberculosis.",
            "A reason not to commit suicide.",
            "Going to a high school reunion on ketamine.",
            "The passage of time.",
            "Child support payments.",
            "Changing a person's mind with logic and facts.",
            "My boyfriend's stupid penis.",
            "The tiger that killed my father.",
            "Genghis Khan's DNA.",
            "Boring vaginal sex.",
            "40 acres and a mule.",
            "A whole new kind of porn.",
            "Slowly easing down onto a cucumber.",
            "Wearing glasses and sounding smart.",
            "AIDS monkeys.",
            "A team of lawyers.",
            "Getting drive-by shot.",
            "Not believing in giraffes.",
            "Anal fissures like you wouldn't believe.",
            "A giant powdery manbaby.",
            "Cutting off a flamingo's legs with garden shears.",
            "P.F. Chang himself.",
            "An uninterrupted history of imperialism and exploitation.",
            "A one-way ticket to Gary, Indiana.",
            "Daddy's credit card.",
            "September 11th, 2001.",
            "An unforgettable quinceañera.",
            "Deez nuts.",
            "Social justice warriors with flamethrowers of compassion.",
            "Some shit-hot guitar licks.",
            "Butt stuff.",
            "Blackface.",
            "Blowjobs for everyone.",
            "Getting eaten alive by Guy Fieri.",
            "Western standards of beauty.",
            "Ejaculating live bees and the bees are angry.",
            "My dead son's baseball glove.",
            "Getting caught by the police and going to jail.",
            "A face full of horse cum.",
            "Free ice cream, yo.",
            "The white half of Barack Obama.",
            "The black half of Barack Obama.",
            "An inability to form meaningful relationships.",
            "A bass drop so huge it tears the starry vault asunder to reveal the face of God.",
            "Growing up chained to a radiator in perpetual darkness.",
            "Shitting all over the floor like a bad, bad girl.",
            "A buttload of candy.",
            "Sucking all the milk out of a yak.",
            "Bullets.",
            "A man who is so cool that he rides on a motorcycle.",
            "Sudden penis loss.",
            "Getting all offended.",
            "Crying and shitting and eating spaghetti.",
            "One unforgettable night of passion.",
            "Being popular and good at sports.",
            "Filling a man's anus with concrete.",
            "Two whales fucking the shit out of eachother.",
            "Cool, relateable cancer teens.",
            "The amount of gay I am.",
            "A possible Muslim.",
            "Unsheathing my massive horse cock.",
            "A bowl of gourds.",
            "The male gaze.",
            "The power of the Dark Side.",
            "Ripping a dog in half.",
            "A constant need for validation.",
            "Meaningless sex.",
            "Such a big boy.",
            "Throwing stones at a man until he dies.",
            "Cancer.",
            "Like a million alligators.",
            "Eating together like a god damn family for once.",
            "Cute boys.",
            "Pussy.",
            "Being a terrible mother.",
            "Never having sex again.",
            "A pizza guy who fucked up.",
            "A whole lotta woman.",
            "The all-new Nissan Pathfinder with 0.9% APR financing!",
            "A peyote-fueled vision quest.",
            "Kale.",
            "Breastfeeding a ten year old.",
            "Crippling social anxiety.",
            "Immortality cream.",
            "Texas.",
            "Teaching a girl how to handjob the penis.",
            "A turd.",
            "Shapes and colors.",
            "Whatever you wish, mother.",
            "The haunting stare of an Iraqi child.",
            "Robots who just want to party.",
            "A self-microwaving burrito.",
            "Forgetting grandma's first name.",
            "Our new Buffalo Chicken Dippers®!",
            "Treasures beyond your wildest dreams.",
            "Getting shot out of a cannon.",
            "The sweet song of sword against and the braying of mighty war beasts.",
            "Walking into a glass door.",
            "The color \"puce\".",
            "Every ounce of charisma left in Mick Jagger's tired body.",
            "The eighth graders.",
            "Setting my balls on fire and cartwheeling to Ohio.",
            "The dentist.",
            "Gwyneth Paltrow's opinions.",
            "Turning the rivers red with the blood of infidels.",
            "Rabies.",
            "Important news about Taylor Swift.",
            "Ejaculating inside another man's wife.",
            "Owls, the perfect predator.",
            "Being John Malkovich.",
            "Bathing in moonsblood and dancing around the ancient oak.",
            "An oppressed people with a vibrant culture.",
            "An overwhelming variety of cheeses.",
            "Reading the entire End-User License Agreement.",
            "Morpheus.",
            "Peeing into a girl's butt to make a baby.",
            "Generally having no idea of what's going on.",
            "No longer finding any Cards Against Humanity card funny.",
            "Several Michael Keatons.",
            "A bus that will explode if it goes under 50 miles per hour.",
            "Sucking the President's dick.",
            "Sunny D! Alright!",
            "A mulatto, an albino, a mosquito, and my libido.",
            "Log™;.",
            "Jerking off to a 10-second RealMedia clip.",
            "The Y2K bug.",
            "Deregulating the mortgage market.",
            "Stabbing the shit out of a Capri Sun.",
            "Wearing Nicolas Cage's face.",
            "Freeing Willy.",
            "Kurt Cobain's death.",
            "The Great Cornholio.",
            "Liking big butts and not being able to lie about it.",
            "Yelling \"girl power!\" and doing a high kick.",
            "Pure Moods, Vol. 1.",
            "Pizza in the morning, pizza in the evening, pizza at supper time.",
            "Pamela Anderson's boobs running in slow motion.",
            "Getting caught up in the CROSSFIRE™;.",
            "Angels interfering in an otherwise fair baseball game.",
            "Cool 90s up-in-the-front hair.",
            "Patti Mayonnaise.",
            "The biggest, blackest dick.",
            "A box within a box.",
            "A boxing match with a giant box.",
            "A box.",
            "Pandora's vagina.",
            "Former President George W. Box.",
            "Being a motherfucking box.",
            "A falcon with a box on its head.",
            "Two midgets shitting into a box.",
            "A box without hinges, key, or lid, yet golden treasure inside is hid.",
            "The J15 Patriot Assault Box.",
            "An alternate universe in which boxes store things inside of people.",
            "A box that is conscious and wishes it weren't a box.",
            "Something that looks like a box but turns out to be a crate.",
            "A man-shaped box.",
            "A box-shaped man.",
            "Boxing up my feelings.",
            "A world without boxes.",
            "The Boxcar Children.",
            "An outbreak of smallbox.",
            "A box of biscuits, a box of mixed biscuits, and a biscuit mixer.",
            "A CGI dragon.",
            "A dwarf who won't leave you alone until you compare penis sizes.",
            "A gay sorcerer who turns everyone gay.",
            "A ghoul.",
            "A Hitachi Magic Wand.",
            "A magical kingdom with dragons and elves and no black people.",
            "A mysterious, floating orb.",
            "A weed elemental who gets everyone high.",
            "Accidentally conjuring a legless horse that can't stop ejaculating.",
            "Bathng naked in a moonlit grove.",
            "Dinosaurs who wear armor and you ride them and they kick ass.",
            "Eternal darkness.",
            "Freaky, pan-dimensional sex with a demigod.",
            "Gender equality.",
            "Going on an epic adventure and learning a valuable lesson about friendship.",
            "Handcuffing a wizard to a radiator and dousing him with kerosene.",
            "Hodor.",
            "How hot Orlando Bloom was in Lord of the Rings.",
            "Kneeing a wizard in the balls.",
            "Make-believe stories for autistic white men,",
            "Reading The Hobbit under the covers while mom and dad scream at each other downstairs.",
            "Shitting in a wizard's spell book and jizzing in his hat.",
            "Shooting a wizard with a gun.",
            "The all-seeing Eye of Sauron.",
            "The card game Neil Gaiman wrote: \"Three elves at a time.\"",
            "True love's kiss.",
            "A sobering quantity of chili cheese fries.",
            "Going vegetarian and feeling so great all the time.",
            "Kale farts.",
            "Licking the cake batter off of grandma's fingers.",
            "Real cheese flavor.",
            "Swishing the wine around and sniffing it like a big fancy man.",
            "The Dial-A-Slice Apple Divider from Williams-Sonoma.",
            "What to do with all of this chocolate on my penis.",
            "A belly full of hard-boiled eggs.",
            "A joyless vegan patty.",
            "A table for one at The Cheesecake Factory.",
            "Being emotionally and physically dominated by Gordon Ramsay.",
            "Kevin Bacon Bits.",
            "Not knowing what to believe anymore about butter.",
            "Soup that's better than pussy.",
            "Sucking down thousands of pounds of krill every day.",
            "A Mexican child trapped inside of a burrito.",
            "Clamping down on a gazelle's jugular and tasting its warm life waters.",
            "Committing suicide at the Old Country Buffet.",
            "Father's forbidden chocolates.",
            "Jizz Twinkies.",
            "The Hellman's Mayonnaise Corporation.",
            "The hot dog I put in my vagina ten days ago.",
            "The inaudible screams of carrots.",
            "A supermassive black hole.",
            "Reconciling quantum theory with general relativity.",
            "Electroejaculating a capuchin monkey.",
            "Insufficient serotonin.",
            "Evolving a labyrinthine vagina.",
            "Getting really worried about global warming for a few seconds.",
            "Infinity.",
            "Oxytocin release via manual stimulation of the nipples.",
            "Uranus.",
            "Being knowledgeable in a narrow domain that nobody understands or cares about.",
            "Achieving reproductive success.",
            "Slowly evaporating.",
            "The quiet majesty of the sea turtle.",
            "A 0.7 waist-to-hip ratio.",
            "Fun and interesting facts about rocks.",
            "Photosynthesis.",
            "Developing secondary sex characteristics.",
            "Failing the Turing test.",
            "Explosive decompression.",
            "Driving into a tornado to learn about tornadoes.",
            "David Attenborough watching us mate.",
            "3.7 billion years of evolution.",
            "The Sun engulfing the Earth.",
            "A complete inability to understand anyone else's perspective.",
            "A fun, sexy time at the nude beach.",
            "A man from Craigslist.",
            "A night of Taco Bell and anal sex.",
            "A respectful discussion of race and gender on the Internet.",
            "Cat massage.",
            "Destroying Dick Cheney's last horcrux.",
            "Game of Thrones spoilers.",
            "Getting teabagged by a fifth grader in Call of Duty.",
            "Goats screaming like people.",
            "Googling.",
            "Internet porn analysis paralysis.",
            "Matching with Mom on Tinder.",
            "My browser history.",
            "My privileged white penis.",
            "Pretending to be black.",
            "Smash Mouth.",
            "Taking a shit while running at full speed.",
            "That thing on the Internet everyone's talking about.",
            "Three years of semen in a shoebox.",
            "YouTube comments.",
            "The Bernie Sanders revolution.",
            "Letting Bernie Sanders rest his world-weary head on your lap.",
            "A beautiful, ever-expanding circle of inclusivity that will never include Republicans.",
            "Black lives mattering.",
            "Donald Trump holding his nose while he eats pussy.",
            "The fact that Hillary Clinton is a woman.",
            "Kicking the middle class in the balls with a regressive tax code.",
            "Keeping the government out of my vagina.",
            "The systematic disenfranchisement of black voters.",
            "Increasing economic and political polarization",
            "Eating the president's pussy.",
            "Actually voting for Donald Trump to be President of the actual United States.",
            "A liberal bias.",
            "Hating Hillary Clinton.",
            "Growing up and becoming a Republican.",
            "Courageously going ahead with that racist comment.",
            "Dispelling this fiction that Barack Obama doesn't know what he's doing.",
            "Jeb!",
            "The good, hardworking people of Dubuque, Iowa.",
            "Conservative talking points.",
            "Shouting the loudest",
            "Sound of fiscal policy.",
            "Full-on socialism.",
            "Santa's heavy sack.",
            "Clearing a bloody path through Walmart with a scimitar.",
            "Another shitty year.",
            "Whatever Kwanzaa is supposed to be about.",
            "A Christmas stocking full of coleslaw.",
            "Elf cum.",
            "The tiny, calloused hands of the Chinese children that made this card.",
            "Taking down Santa with a surface-to-air missle.",
            "Several intertwining love stories featuring Hugh Grant.",
            "Mall Santa.",
            "My hot cousin.",
            "The Star Wars Holiday Special.",
            "Krampus, the Austrian Christmas monster.",
            "Pretending to be happy.",
            "Socks. ",
            "Eating an entire snowman.",
            "A toxic family environment.",
            "A visually arresting turtleneck.",
            "Fucking up \"Silent Night\" in front of 300 parents.",
            "Immaculate conception.",
            "Space Jam on VHS.",
            "Gift-wrapping a live hamster.",
            "A Hungry-Man™; Frozen Christmas Dinner for One.",
            "Swapping bodies with mom for a day.",
            "Making up for 10 years of shitty parenting with a PlayStation.",
            "Finding out that Santa isn't real.",
            "Slicing a ham in icy silence.",
            "The shittier, Jewish version of Christmas.",
            "The Hawaiian goddess Kapo and her flying detachable vagina.",
            "Having a strong opinion about Obamacare.",
            "The royal afterbirth.",
            "Congress's flaccid penises withering away beneath their suit pants.",
            "Piece of shit Christmas cards with no money in them.",
            "Moses gargling Jesus's balls while Shiva and the Buddha penetrate his divine hand holes.",
            "Giving money and personal information to strangers on the Internet.",
            "These low, low prices!",
            "A magical tablet containing a world of unlimited pornography.",
            "People with cake in their mouths talking about how good cake is.",
            "Jizzing into Santa's beard.",
            "A simultaneous nightmare and wet dream starring Sigourney Weaver.",
            "Being blind and deaf and having no limbs.",
            "Rudolph's bright red balls.",
            "The Grinch's musty, cum-stained pelt.",
            "Breeding elves for their priceless semen.",
            "Forcing a handjob on a dying man. ",
            "A homoerotic subplot.",
            "An origami swan that's some kind of symbol?",
            "25 shitty jokes about House of Cards.",
            "My constituents.",
            "Punching a congressman in the face.",
            "Strangling a dog to make a point to the audience.",
            "A childless marriage.",
            "A much younger woman.",
            "An older man.",
            "Getting eaten out while on the phone with Dad.",
            "Making it look like a suicide.",
            "Carbon monoxide poisoning. ",
            "Discharging a firearm in a residential area.",
            "Ribs so good they transcend race and class.",
            "The sensitive European photographer who's fucking my wife."
        };
    }
}